# Generated by Django 3.1.4 on 2020-12-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201209_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
